### ISSUE TITLE
Pre-OSS Checklist

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/dart_dev#11]
- [x] dartfmt line length option #14 
- [x] Tests #15 
- [x] Licenses #17 
- [x] Update installation instructions to point to actual version (or get rid of it in favor or auto generated version on Pub) #33 
- [x] Changelog #12 
- [x] Prep pubspec.yaml #27 
- [x] Travis CI setup #29 
- [x] Codecov.io setup #30

**Comment by evanweible-wf** [comment]
All ready!
