### ISSUE TITLE
CP-2565 V2: analyze

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/dart_dev#172]
## `ddev analyze`

This task proxies the `dartanalyzer` executable that is distributed with the Dart SDK. 
### Package Configuration

The `dartanalyzer` executable supports its own configuration file `analysis_options.yaml`. This is documented here: https://pub.dartlang.org/packages/analyzer. An example is included here for convenience:

**analysis_options.yaml**

``` yaml
analyzer:
  exclude:
    - test/_data/p4/lib/lib1.dart
    - test/_data/p5/p5.dart
    - test/_data/bad*.dart
    - test/_brokendata/**
  strong-mode: true

linter:
  rules:
    - camel_case_types
    - empty_constructor_bodies
```

For configuration beyond what is supported by `dartanalyzer` above, use the `dart_dev.yaml` configuration file.

**dart_dev.yaml**

``` yaml
analyze:
  # Specify a default list of libraries to analyze
  libraries:
    - example/index.dart
    - lib/entry_point.dart
    - test/unit_test.dart
```
### Command Line Configuration

As this is a proxy for the `dartanalyzer` executable, it shares the same command line flags, options, and arguments.

```
$ pub run dart_dev analyze -h

Usage: pub run dart_dev analyze [options...] <libraries to analyze...>

The dart_dev analyze task proxies dartanalyzer.

:: Package Configuration
------------------------

  ======== Libraries to be Analyzed (from dart_dev.yaml)
  - example/index.dart
  - lib/entry_point.dart
  - test/unit_test.dart

  ======== Excluded Files (from analysis_options.yaml/.analysis_options)
  - test/_data/p4/lib/lib1.dart
  - test/_data/p5/p5.dart
  - test/_data/bad*.dart
  - test/_brokendata/**

  ======== Lint Rules (from analysis_options.yaml/.analysis_options)
  - camel_case_types
  - empty_constructor_bodies

:: Command Line Options: dart_dev analyze
------------------------------------

  Usage: pub run dart_dev analyze [options...] <libraries to analyze...>

:: Command Line Options: dartanalyzer
------------------------------------

  Usage: dartanalyzer [options...] <libraries to analyze...>
  -b, --batch                        Read commands from standard input (for testing).
      --dart-sdk                     The path to the Dart SDK.
      --packages                     Path to the package resolution configuration file, which supplies a mapping of package names to paths.  This option cannot be used with --package-root.
  -p, --package-root                 Path to a package root directory (deprecated). This option cannot be used with --packages.
      --options                      Path to an analysis options file.
      --format                       Specifies the format in which errors are displayed.
      --machine                      Print errors in a format suitable for parsing (deprecated).
      --version                      Print the analyzer version.
      --lints                        Show lint results.
      --no-hints                     Do not show hint results.
      --ignore-unrecognized-flags    Ignore unrecognized command line flags.
      --fatal-hints                  Treat hints as fatal.
      --fatal-warnings               Treat non-type warnings as fatal.
      --fatal-lints                  Treat lints as fatal.
      --package-warnings             Show warnings from package: imports.
      --show-package-warnings        Show warnings from package: imports (deprecated).
      --warnings                     Show warnings from SDK imports.
      --show-sdk-warnings            Show warnings from SDK imports (deprecated).
      --x-perf-report                Writes a performance report to the given file (experimental).
  -h, --help                         Display this help message.
      --url-mapping                  --url-mapping=libraryUri,/path/to/library.dart directs the analyzer to use "library.dart" as the source for an import of "libraryUri".
      --[no-]strong                  Enable strong static checks (https://goo.gl/DqcBsw)
      --no-implicit-casts            Disable implicit casts in strong mode (https://goo.gl/cTLz40)
      --no-implicit-dynamic          Disable implicit dynamic (https://goo.gl/m0UgXD)

For more information, see http://www.dartlang.org/tools/analyzer.
```
### Detecting Un-Analyzed Files

By allowing consumers to configure the default list of libraries to analyze, there is a risk that this list will become outdated. We can help mitigate this by comparing the set of analyzed files against the set of `.dart` files in the package (minus the explicitly excluded files) and logging a warning when we detect that there are one or more files not being analyzed.
### Task List
- [ ] **Move `analyzer` from dependency to dev dependency**
  - [ ] Detect when `analyzer` dependency is missing and warn
  - [ ] Attempt to establish a compatibility range and warn when `analyzer` dependency is outside of it
- [ ] **`dart_dev.yaml` configuration**
  - [ ] Default list of libraries to analyze
- [ ] **Pass unused command line options to the `dartanalyzer` executable**
- [ ] **Implement help/usage output (see above)**
- [ ] **Detect un-analyzed files**

**Comment by rmconsole3-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/dart_dev/172/addTicketToTitle'>here</a> to have Rosie create one for you.
