### ISSUE TITLE
CP-2566 V2: apply-license

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/dart_dev#173]
## `ddev apply-license`

Apply the contents of a license file (`LICENSE` by default) to a set of source files as a header comment. The license file and the files to which this header is applied is configurable.
### Supported File Types
- CSS (`*.css`)
- Dart (`*.dart`)
- HTML (`*.html`)
- JS (`*.js`)
- SASS (`*.sass`)
- SCSS (`*.scss`)
### Package Configuration

**dart_dev.yaml**

``` yaml
apply-license:
  license: LICENSE.md
  include:
    - example/**
    - lib/**
    - tool/serve.dart
  exclude:
    - lib/src/generated_file.dart
    - generated/**
```
### Command Line Configuration

```
Usage: pub run dart_dev apply-license [options...]

:: Package Configuration
------------------------

  ======== License File
  LICENSE

  ======== Included Files
  - example/**
  - lib/**
  - tool/serve.dart

  ======== Excluded Files
  - lib/src/generated_file.dart
  - generated/**

:: Command Line Options
-----------------------

  -u, --update-from                 Path to the old license file to update from. New license will be read from the configured location.
```
### Updating Existing License Headers

License files often have dates in them, which means they eventually need to be updated. We can make this process easy with something like this:

```
$ pub run dart_dev apply-license --update-from OLD_LICENSE.md
```
### Task List
- [ ] **`dart_dev.yaml` configuration**
  - [ ] License file path
  - [ ] Include/exclude globs
- [ ] **File type support**
  - [x] `.css`
  - [x] `.dart`
  - [x] `.html`
  - [x] `.js`
  - [ ] `.sass`
  - [ ] `.scss`
- [ ] **Support updating existing license headers** (`--update-from`)

**Comment by rm-astro-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/dart_dev/173/addTicketToTitle'>here</a> to have Rosie create one for you.
