### ISSUE TITLE
WP-4212 CP-2569 V2: format

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/dart_dev#176]
## `ddev format`

This task proxies the `dartfmt` executable from the `dart_style` package. 
### Package Configuration

**dart_dev.yaml**

``` yaml
format:
  # Include and/or exclude files (globs supported)
  include:
    - example/**
    - lib/**
    - test/**
  exclude:
    - lib/src/generated/**

  # Configure the maximum line length
  line-length: 100
```
### Command Line Configuration

As this is a proxy for the `dartfmt` executable, it shares the same command line flags, options, and arguments.

```
$ pub run dart_dev format -h

Usage: pub run dart_dev format [-n|-w] [files or directories...]

The dart_dev format task proxies dartfmt.

:: Package Configuration
------------------------

  ======== Files to be Formatted (from dart_dev.yaml)
  - example/**
  - lib/**
  - test/**

  ======== Excluded Files (from dart_dev.yaml)
  - lib/src/generated/**

  ======== Other Options (from dart_dev.yaml)
  - Line-length: 100

:: Command Line Options: dartfmt
------------------------------------

  Reformats whitespace in Dart source files.

  Usage: dartfmt [-n|-w] [files or directories...]

  -h, --help            Shows usage information.
      --version         Shows version information.
  -l, --line-length     Wrap lines longer than this.
                        (defaults to "80")

  -i, --indent          Spaces of leading indentation.
                        (defaults to "0")

      --preserve        Selection to preserve, formatted as "start:length".
  -n, --dry-run         Show which files would be modified but make no changes.
  -w, --overwrite       Overwrite input files with formatted output.
  -m, --machine         Produce machine-readable JSON output.
      --profile         Display profile times after running.
      --follow-links    Follow links to files and directories.
                        If unset, links will be ignored.

  -t, --transform       Unused flag for compability with the old formatter.
```
### Task List
- [ ] **Move `dart_style` from dependency to dev dependency**
  - [ ] Detect when `dart_style` dependency is missing and warn
  - [ ] Attempt to establish a compatibility range and warn when `dart_style` dependency is outside of it
- [ ] **`dart_dev.yaml` configuration**
  - [ ] Include/Exclude
  - [ ] Line length
- [ ] **Pass unused command line options to the `dartfmt` executable**
- [ ] **Implement help/usage output (see above)**

**Comment by rm-astro-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/dart_dev/176/addTicketToTitle'>here</a> to have Rosie create one for you.
