### ISSUE TITLE
CP-2564 V2: serve

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/dart_dev#178]
## `ddev serve`

This task proxies the `pub serve` command.
### Package Configuration

**dart_dev.yaml**

``` yaml
analyze:
  # Map the directories to serve to the ports to serve them on
  directories:
    example: 9000
    test: 9001
    web: 9002

```
### Command Line Configuration

As this is a proxy for the `pub serve` executable, it shares the same command line flags, options, and arguments.

```
$ pub run dart_dev serve -h

Usage: pub run dart_dev serve [directories...]

The dart_dev serve task proxies `pub serve`.

:: Package Configuration
------------------------

  ======== Directories to be Served (from dart_dev.yaml)
  - http://localhost:9000   example/
  - http://localhost:9001   test/
  - http://localhost:9002   web/

:: Command Line Options: pub serve
------------------------------------

  Run a local web development server.

  By default, this serves "web/" and "test/", but an explicit list of
  directories to serve can be provided as well.

  Usage: pub serve [directories...]
  -h, --help               Print this usage information.
      --mode               Mode to run transformers in.
                           (defaults to "debug")

      --all                Use all default source directories.
  -D, --define             Defines an environment constant for dart2js.
      --hostname           The hostname to listen on.
                           (defaults to "localhost")

      --port               The base port to listen on.
                           (defaults to "8080")

      --[no-]dart2js       Compile Dart to JavaScript.
                           (defaults to on)

      --[no-]force-poll    Force the use of a polling filesystem watcher.

  Run "pub help" to see global options.
  See http://dartlang.org/tools/pub/cmd/pub-serve.html for detailed documentation.
```
### Task List
- [ ] **`dart_dev.yaml` configuration**
  - [ ] Map of directories to ports
  - [ ] Reverse proxy (would allow client-side routing and proxying to other backend servers)
- [ ] **Pass unused command line options to the `pub serve` executable**
- [ ] **Implement help/usage output (see above)**

**Comment by rmconsole-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/dart_dev/178/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by maxwellpeterson-wf** [comment]
Command line configuration section contains references to analyze task (bad copy paste)

**Comment by maxwellpeterson-wf** [comment]
Will this attempt to address the reverse proxying of back end requests or handle URLs from client-side routing at all or will that remain a local task override?

**Comment by evanweible-wf** [comment]
@maxwellpeterson-wf forgot about that - I've added it to the task list

**Comment by travissanderson-wf** [comment]
--mode=release would be nice

**Comment by evanweible-wf** [comment]
Added in v3.
