### ISSUE TITLE
CP-2571 V2: test

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/dart_dev#179]
## `ddev test`

This task proxies the `test` executable from the `test` package.
### Package Configuration

The `test` package supports its own configuration file `dart_test.yaml`. This is documented here: https://github.com/dart-lang/test/blob/master/doc/configuration.md. The configuration options available there are very extensive, and for that reason it is not necessary for dart_dev to support any additional configuration in the `dart_dev.yaml` file.
### Command Line Configuration

As this is a proxy for the `test` executable, it shares the same command line flags, options, and arguments.

```
$ pub run dart_dev test -h

Usage: pub run dart_dev test [files or directories...]

The dart_dev test task proxies pub run test.

:: Command Line Options: pub run test
------------------------------------

  Runs tests in this package.

  Usage: pub run test [files or directories...]

  -h, --help                     Shows this usage information.
      --version                  Shows the package's version.

  ======== Selecting Tests
  -n, --name                     A substring of the name of the test to run.
                                 Regular expression syntax is supported.
                                 If passed multiple times, tests must match all substrings.

  -N, --plain-name               A plain-text substring of the name of the test to run.
                                 If passed multiple times, tests must match all substrings.

  -t, --tags                     Run only tests with all of the specified tags.
                                 Supports boolean selector syntax.

  -x, --exclude-tags             Don't run tests with any of the specified tags.
                                 Supports boolean selector syntax.

      --[no-]run-skipped         Run skipped tests instead of skipping them.

  ======== Running Tests
  -p, --platform                 The platform(s) on which to run the tests.
                                 [vm (default), dartium, content-shell, chrome, phantomjs, firefox, safari]

  -P, --preset                   The configuration preset(s) to use.
  -j, --concurrency=<threads>    The number of concurrent test suites run.
                                 (defaults to "4")

    --pub-serve=<port>         The port of a pub serve instance serving "test/".
      --timeout                  The default test timeout. For example: 15s, 2x, none
                                 (defaults to "30s")

      --pause-after-load         Pauses for debugging before any tests execute.
                                 Implies --concurrency=1 and --timeout=none.
                                 Currently only supported for browser tests.

  ======== Output
  -r, --reporter                 The runner used to print test results.

            [compact]            A single line, updated continuously.
            [expanded]           A separate line for each update.
            [json]               A machine-readable format (see https://goo.gl/gBsV1a).

      --verbose-trace            Whether to emit stack traces with core library frames.
      --js-trace                 Whether to emit raw JavaScript stack traces for browser tests.
      --[no-]color               Whether to use terminal colors.
                                 (auto-detected by default)
```
### Making Tags/Presets Discoverable

When you jump into a new project, it is not always obvious what the testing setup is. If packages are utilizing tags and presets, we could detect this and log them to the user when the `-h` flag is passed in. This would make it easier as a contributor to discover the different suites of tests that can be run.
### Task List
- [ ] **Move `test` from dependency to dev dependency**
  - [ ] Detect when `test` dependency is missing and warn
  - [ ] Attempt to establish a compatibility range and warn when `test` dependency is outside of it
- [ ] **Pass unused command line options to the `test` executable**
- [ ] **Implement help/usage output (see above)**
- [ ] **Detect and log tags/prests**

**Comment by rmconsole-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/dart_dev/179/addTicketToTitle'>here</a> to have Rosie create one for you.
