### ISSUE TITLE
CP-2612 V2: sort-imports

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/dart_dev#180]
## `ddev sort-imports`

This task sorts imports into logical groups and alphabetizes each group.
### Package Configuration

There won't be any additional configuration for this specific task, but it will utilize the configurations from `analysis_options.yaml` and `dart_dev.yaml` to determine which files should be analyzed/formatted.

The set of files for which imports should be sorted is determined by configuration in the `dart_dev.yaml` file:

``` yaml
sort-imports:
  # Include and/or exclude files (globs supported)
  include:
    - example/**
    - lib/**
    - test/**
  exclude:
    - lib/src/generated/**
```

If you omit the above configuration altogether, the `sort-imports` task will inherit the configuration from the `format` task.
### Command Line Configuration

There aren't any command line options at this point.

```
$ pub run dart_dev sort-imports -h

Usage: pub run dart_dev sort-imports [options...] <libraries to analyze...>

:: Package Configuration
------------------------

  ======== Files to have Imports Sorted (from dart_dev.yaml)
  - example/**
  - lib/**
  - test/**

  ======== Excluded Files (from dart_dev.yaml)
  - lib/src/generated/**
```
### `--check`

Similar to the `format` task, we need to support a `--check` flag that will run the task without actually making any changes and exit with a non-zero code if there are changes that would have been made.
### Task List
- [ ] **`dart_dev.yaml` configuration**
  - [ ] Include/Exclude
  - [ ] Inherit from `format` configuration if `sort-imports` configuration is omitted
- [ ] **Implement help/usage output (see above)**
- [ ] **`--check`**

**Comment by rmconsole2-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/dart_dev/180/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by evanweible-wf** [comment]
This is covered by a lint, now, and IDEs even support auto-sorting.
